export const productCopy = {
  appName: "Path Import",
  downloadAppLabel: "Download on the App Store",
  appDownloadHref: "https://apps.apple.com/app/id6758724528",
  navHomeLabel: "Path Import home",
  heroTitle: "Convert Arc and Moves backups locally",
  heroBody: "Select a backup folder. Path Import creates a database file locally.",
  selectFolderLabel: "Select backup folder",
  workingStep: "Step 2 of 3",
  workingTitle: "Converting data",
  workingBody: "Path Import is reading files, resolving overlaps, and preparing your database.",
  workingFallback: "Preparing files",
  completeStep: "Step 3 of 3",
  completeTitle: "Import file ready",
  completeSavedBody: "Your import database was saved in the selected folder. Open Path on your iPhone and import it from Settings.",
  completeDownloadBody: "Your import database downloaded automatically. Open Path on your iPhone and import it from Settings.",
  savedStatus: "Saved to disk",
  downloadAgainLabel: "Download again",
  chooseAnotherLabel: "Choose another folder",
  errorTitle: "This folder was not recognized",
  errorFallback: "Choose the folder that contains Arc Export, Arc Previous Backups, or Moves json/daily/storyline.",
  errorUnknownTitle: "Something went wrong",
  privacyOne: "No upload",
  privacyTwo: "No account",
  privacyThree: "No tracking"
} as const;
